CREATE TABLE autor (
    id bigint generated by DEFAULT AS identity,
    apellido varchar(255),
    nombre varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE autor_titulos (
    autor_id bigint NOT NULL,
    titulos_id bigint NOT NULL
);

CREATE TABLE ejemplar (
    id bigint generated by DEFAULT AS identity,
    titulo_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE prestamo (
    id bigint generated by DEFAULT AS identity,
    activo boolean,
    fecha_fin timestamp,
    fecha_inicio timestamp,
    ejemplar_id bigint,
    titulo_id bigint,
    usuario_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE reserva (
    id bigint generated by DEFAULT AS identity,
    fecha date,
    titulo_id bigint,
    usuario_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE titulo (
    dtype varchar(31) NOT NULL,
    id bigint generated by DEFAULT AS identity,
    isbn varchar(255),
    num_reserva varchar(255),
    titulo varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE titulo_autores (
    titulo_id bigint NOT NULL,
    autores_id bigint NOT NULL
);

CREATE TABLE titulo_ejemplares (
    titulo_id bigint NOT NULL,
    ejemplares_id bigint NOT NULL
);

CREATE TABLE titulo_prestamos (
    titulo_id bigint NOT NULL,
    prestamos_id bigint NOT NULL
);

CREATE TABLE titulo_reservas (
    titulo_id bigint NOT NULL,
    reservas_id bigint NOT NULL
);

CREATE TABLE usuario (
    id bigint generated by DEFAULT AS identity,
    apellidos varchar(255),
    fecha_fin_penalizacion timestamp,
    nombre varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE usuario_prestamos (
    usuario_id bigint NOT NULL,
    prestamos_id bigint NOT NULL
);

CREATE TABLE usuario_reservas (
    usuario_id bigint NOT NULL,
    reservas_id bigint NOT NULL
);


ALTER TABLE titulo_ejemplares
ADD CONSTRAINT UK_cfn9b7uxogif59edjllkyh28k UNIQUE (ejemplares_id);

ALTER TABLE  titulo_prestamos
ADD CONSTRAINT UK_1tj4spj37fj82nc2dg2uds7cg UNIQUE (prestamos_id);

ALTER TABLE titulo_reservas
ADD CONSTRAINT UK_tgyb7xbp8uc6j90xug3xl598l UNIQUE (reservas_id);

ALTER TABLE usuario_prestamos
ADD CONSTRAINT UK_ip6phtqsbttqqedvhoyqv4j1h UNIQUE (prestamos_id);

ALTER TABLE usuario_reservas
ADD CONSTRAINT UK_6xal95jkvo1rk1ww04hlwl15h UNIQUE (reservas_id);

ALTER TABLE autor_titulos
ADD CONSTRAINT FK2d65wmh66ya7gcmm8cxgbw04v FOREIGN KEY (titulos_id) REFERENCES titulo;

ALTER TABLE autor_titulos
ADD CONSTRAINT FKoovn053c7xv4gh5ug9i3uwvrp FOREIGN KEY (autor_id) REFERENCES autor;

ALTER TABLE ejemplar
ADD CONSTRAINT FKqly7r236t66o90h3xubnvrot7 FOREIGN KEY (titulo_id) REFERENCES titulo;


ALTER TABLE prestamo
ADD CONSTRAINT FKiq1nrc3dah91m2ug85kjk950g FOREIGN KEY (ejemplar_id) REFERENCES ejemplar;

ALTER TABLE prestamo
ADD CONSTRAINT FKnl70cr8cb2ywkp1ijos9sqxiq FOREIGN KEY (titulo_id) REFERENCES titulo;

ALTER TABLE prestamo
ADD CONSTRAINT FKqxhq6d4w6fuv27c7j3af28wdu FOREIGN KEY (usuario_id) REFERENCES usuario;

ALTER TABLE reserva
ADD CONSTRAINT FKm8t8m28ovrnlbugvijs2jkyni FOREIGN KEY (titulo_id) REFERENCES titulo;

ALTER TABLE  reserva
ADD CONSTRAINT FKiad9w96t12u3ms2ul93l97mel FOREIGN KEY (usuario_id) REFERENCES usuario;


ALTER TABLE titulo_autores
ADD CONSTRAINT FKnqqqr2hvkeby0a49d03dfvfcw FOREIGN KEY (autores_id) REFERENCES autor;


ALTER TABLE titulo_autores
ADD CONSTRAINT FKl5qdu4grtj04bwdwfhyg67bap FOREIGN KEY (titulo_id) REFERENCES titulo;


ALTER TABLE titulo_ejemplares
ADD CONSTRAINT FKbr531njurh9f78cw3u2u2b1r7 FOREIGN KEY (ejemplares_id) REFERENCES ejemplar;


ALTER TABLE titulo_ejemplares
ADD CONSTRAINT FKfjdmxy4qvrm2sfeosklxna7n4 FOREIGN KEY (titulo_id) REFERENCES titulo;


ALTER TABLE titulo_prestamos
ADD CONSTRAINT FKno7ngqnxpu21b14m4gliij2 FOREIGN KEY (prestamos_id) REFERENCES prestamo;

ALTER TABLE titulo_prestamos
ADD CONSTRAINT FKhjxovlxfm1oirykppw6i017xt FOREIGN KEY (titulo_id) REFERENCES titulo;

ALTER TABLE titulo_reservas
ADD CONSTRAINT FK3rt63mexpey5my1eiac5uxy1x FOREIGN KEY (reservas_id) REFERENCES reserva;

ALTER TABLE titulo_reservas
ADD CONSTRAINT FK8u06vjy3urlrbgd5l7kmwe0pb FOREIGN KEY (titulo_id) REFERENCES titulo;

ALTER TABLE  usuario_prestamos
ADD CONSTRAINT FK3id2fy6dpyvi52it9dwqh1kol FOREIGN KEY (prestamos_id) REFERENCES prestamo;

ALTER TABLE usuario_prestamos
ADD CONSTRAINT FKoqpf48nll32ie8k6upiasyb8f FOREIGN KEY (usuario_id) REFERENCES usuario;

ALTER TABLE usuario_reservas
ADD CONSTRAINT FKnrstqjflckqwfk38384iporvq FOREIGN KEY (reservas_id) REFERENCES reserva;

ALTER TABLE usuario_reservas
ADD CONSTRAINT FKt5smjpambd9c8tcbpmmlemuh0 FOREIGN KEY (usuario_id) REFERENCES usuario;